### ISSUE TITLE
Reimplement logic of coin capture

### ISSUE THREAD

**Issue by PrajwalKrishna** [PK1210/SuperMario#3]
Right now for seeing a capture of coin the function iterates over all set coins and checks whether some matches with Mario or not. This is highly ineffective and needs to be changed.

**Comment by jrkong** [comment]
I took a look at the code and I have an idea.

Currently coins are created and put into a list. I want to add an additional layer to this by creating a nested dictionary which uses the coin coordinates as keys and stores the coin index in the resulting nest structure (so something like `{"x coordinate"{"y coordinate" = coin index}}). Then instead of checking every coin the dictionary is referenced to check if a coin exists. If it does the coin list is accessed to update the coin's state.

If this sounds like a viable implementation I'll work on it.

**Comment by PrajwalKrishna** [comment]
Nice idea and seems viable you may get going with it

**Comment by PrajwalKrishna** [comment]
@jrkong status?

**Comment by jrkong** [comment]
Currently debugging. I'm thinking that just using the x and y isn't viable because of a few issues:

1. Mario's overall coordinates aren't tracked by the board, he's just identified by the board which means checking Mario's coordinates requires more checks then originally intended. 
1. The math required to calculate Mario's size from his seed coordinates will take roughly as much work as the current coin logic implementation. 

Right now I'm testing moving the coin logic into the board update logic so it removes the coin at the updated location if Mario passes it using the coin dictionary I implemented.

**Comment by PrajwalKrishna** [comment]
Nice
